sources:
  - name: adventure_works
    database: fea_academy
    schema: adventure_works
    tables:
      - name: sales_salesorderheader
      - name: sales_salesorderdetail
      - name: production_product
      - name: sales_customer
      - name: person_person
      - name: person_address
      - name: person_stateprovince
      - name: person_countryregion
      - name: sales_creditcard
      - name: sales_salesreason
      - name: sales_salesorderheadersalesreason